```{r intersect, eval=FALSE}
#install.packages("leaflet")
#install.packages("sf")
#install.packages("dplyr")
#install.packages("rlang")
#update.packages()

library(leaflet)
library(sf)
library(dplyr)
```


##Creating leaflet map/baselayer
```{r intersect, eval=FALSE}
# Createing a leaflet map with center coordinates and zoom level 
map <- leaflet() %>%
  setView(lng =12.565671 , lat = 55.684818, zoom = 13) %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB") %>%
  addLayersControl(
    overlayGroups = c("Green areas", "School districts"),
    options = layersControlOptions(collapsed = FALSE), 
    baseGroups = c("OSM (default)", "CartonDB")
  )

map
```

##Loading data
```{r intersect, eval=FALSE}
# Reading and preparing the first layer - green areas in Copenhagen 
path <- file.path("data/park_groent_omr_oversigtskortPolygon.shp") #path to file
green_areas <- st_read(path)
green_areas <- st_transform(green_areas, crs = "+init=epsg:25832")

green_areas <- st_transform(green_areas, "+proj=longlat +datum=WGS84") #transforming the layer to the WGS84 datum and a long-lat projection

# Checking the CRS of the transformed layer
st_crs(green_areas)
```




```{r intersect, eval=FALSE}
# Reading the second layer -> school districts 
path <- file.path("data/skolegrunddistriktPolygon.shp")
school_districts <- st_read(path)
school_districts <- st_transform(school_districts, crs = "+init=epsg:25832")

school_districts <- st_transform(school_districts, "+proj=longlat +datum=WGS84") #transforming the layer to the WGS84 datum and a long-lat projection

# Checking the CRS of the transformed layer
st_crs(school_districts)
```
```{r}
# Error fix: fixing geometry problems with st_make_valid
green_areas_valid <- st_make_valid(green_areas)
school_districts_valid <- st_make_valid(school_districts)
school_districts_valid$enhedsnavn <- gsub("[^[:alnum:] ]", "", school_districts_valid$enhedsnavn)
school_districts_valid$bydelsnavn <- gsub("[^[:alnum:] ]", "", school_districts_valid$bydelsnavn)
school_districts_valid$udd_distr0 <- gsub("[^[:alnum:] ]", "", school_districts_valid$udd_distr0)
school_districts_valid$cvr_navn <- gsub("[^[:alnum:] ]", "", school_districts_valid$cvr_navn)
school_districts_valid$status <- gsub("[^[:alnum:] ]", "", school_districts_valid$status)

print(school_districts_valid)

# Joining the attribute data and using st_intersection to detect spacial overlay
intersection <- st_intersection(school_districts_valid, green_areas_valid)

#Dataset with number of spacial overlay - number of parks for every school district
dataset <- table(intersection$id)
```

```{r}
# Manually transforming 'dataset' into dataframe
df1 <- data.frame(
  id = c(1:56),
  freq = c(54, 22, 22, 12, 9, 1, 18, 8, 8, 8, 10, 11, 15, 10, 12, 11, 56, 17, 0,  9, 33, 7, 41, 11, 17, 46, 9, 33, 17, 45, 60, 24, 12, 3, 8, 28, 4, 4, 36, 5, 17, 35, 2, 22, 56, 1, 20, 17, 27, 29, 18, 35, 5, 37, 7, 70)
)
```

```{r}
# Joining based on the 'id' column
school_districts_valid <- school_districts_valid %>%
  inner_join(df1, by = c("id" = "id"))
```

##Adding two layers to basemap
```{r}
# Adding school districts with number of parks as label. Label displays when mouse hovers over district
map <- map %>%
  addPolygons(data = school_districts_valid, color = "red", fill= "blue", weight = 2, label=school_districts_valid$freq, , group = "School districts") %>%
  addPolygons(data = green_areas, color = "green", fill = "green", weight = 2, group = "Green areas") 
map
```
##Saving map as html file
```{r}
library(htmlwidgets)
saveWidget(map, file="out/map.html")
```

```{r}
# Creating dataframe with only the park frequency per district and the name of the school district
parks_per_district <- subset(school_districts_valid, select = c("freq", "enhedsnavn"))

parks_per_district
```
##User-generated word produces number of parks 
```{r}
# Prompt extracting school name 
school_name = readline(prompt = "Enter any school name : ");

# Displaying number of parks based on user generated word
if (school_name %in% parks_per_district$enhedsnavn) {
  # Print the row
  filtered_row <- parks_per_district[parks_per_district$enhedsnavn == school_name, ]

# Print the filtered rows
  cat("Number of parks for this school district is: ", parks_per_district[parks_per_district$enhedsnavn == school_name, ]$freq) # Prints the number from freq column that matches the row with the same value as the user-generated word
}
```

##HEATMAP

```{r}
library(ggplot2)
ggplot() +
geom_sf(data = parks_per_district,
        aes(fill = freq),
            color = "white",
            size = 0.1) +
scale_fill_gradient(name = "Number of green areas", 
                    low = "light blue",
                    high = "dark blue") 
ggsave("out/heatmap.png")
```

